[global]
    ## Base Description
    netbios name = Samba Server
    server string = Samba Version %v
    #workgroup = WORKGROUP

    # Network
    smb ports = 445
    socket address = 0.0.0.0
    #hosts_allow = x.x.x.x/255.255.255.0
    #max connections = 0

    ## Logfile
    log file = /smbd/run/%U.log
    max log size = 500

    ## Protocol Settings
    min protocol = SMB2
    server smb encrypt = required 
    #client min protocol = SMB2_02

    ## Authentication
    security = user
    map to guest = Bad User
    # default value
    encrypt passwords = yes
    passdb backend = tdbsam
    guest account = nobody

    ## Performance
    use sendfile = true
    socket options = IPTOS_LOWDELAY TCP_NODELAY 
    min receivefile size = 128k
    aio read size = 0
    aio write size = 65536
    # default value
    server multi channel support = yes
    read raw = yes
    write raw = yes
    large readwrite = yes
    getwd cache = yes
    oplocks = yes
    locking = yes

    ## Files
    # disable windows archive distribution, avoid file "+x" extraly from windows or macos
    map archive = no
    inherit owner = yes
    create mask = 0644
    directory mask = 0755
    delete veto files = yes
    veto files = /._*/.DS_Store/.Trashes/
    # default value
    ea support = yes
    available = yes
    browseable = yes
    guest ok = no

    ## Apple SMB Extensions
    vfs objects = fruit streams_xattr catia
    fruit:metadata = stream
    fruit:nfs_aces = no
    fruit:posix_rename = yes
    fruit:veto_appledouble = no
    fruit:wipe_intentionally_left_blank_rfork = yes
    fruit:delete_empty_adfiles = yes
    fruit:copyfile = yes
    fruit:zero_file_id = yes
    # default value
    fruit:model = MacSamba
    fruit:aapl = yes

    # Printing disabled
    load printers = no
    printcap name = /dev/null
    disable spoolss = yes

[cloud]
    comment = Samba for master
    browseable = no
    # Vaild if path is existing
    path = /smbd/cloud
    writable = yes
    force user = root
    force group = root
    force create mode = 0644
    force directory mode = 0755
    valid users = cloud

[tm]
    comment = Samba for user %u time machine
    fruit:time machine = yes
    fruit:time machine max size = 1T
    available = no
    browseable = no
    # 0750 mode for /smbd/tm
    path = /smbd/tm
    writable = yes
    force directory mode = 0750
    force user = root
    force group = root
    valid users = 
